version: "3.6"

services:
  backend:
    build: ./backend
    ports:
      - "8080"
    env_file:
      - ./config/conf.env
    restart: unless-stopped

  mysql:
    image: mariadb
    volumes:
      - ./config/init-sql.sh:/docker-entrypoint-initdb.d/start.sh
    env_file:
      - ./config/conf.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
      - xpack.security.enabled=false
    restart: unless-stopped

  fpm:
    build: ./php
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./config/conf.env
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - "3020:80"
    depends_on:
      - fpm
      - backend
    volumes:
      - ./frontend:/frontend
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/fastcgi.conf:/etc/nginx/fastcgi.conf
    restart: unless-stopped
