version: "3.3"

services:
  backend:
    build: ./backend
    ports:
      - "8080"
    env_file:
      - ./config/conf.env

  mysql:
    image: mariadb
    volumes:
      - ./config/init-sql.sh:/docker-entrypoint-initdb.d/start.sh
    env_file:
      - ./config/conf.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
      - xpack.security.enabled=false

  fpm:
    build: ./php
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./config/conf.env

  nginx:
    image: nginx
    ports:
      - "3020:80"
    depends_on:
      - fpm
      - backend
    volumes:
      - ./frontend:/frontend
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/fastcgi.conf:/etc/nginx/fastcgi.conf
